-- Migration to add new property fields
ALTER TABLE properties
ADD COLUMN owner TEXT,
ADD COLUMN sale_type TEXT,
ADD COLUMN operation_responsible_id UUID REFERENCES auth.users(id),
ADD COLUMN origin TEXT,
ADD COLUMN registration_number TEXT,
ADD COLUMN landmark TEXT,
ADD COLUMN property_division TEXT,
ADD COLUMN auction_type TEXT,
ADD COLUMN caretaker_id UUID REFERENCES partners(id), -- Assuming partners table exists
ADD COLUMN caretaker_payment_date TEXT,
ADD COLUMN caretaker_notes TEXT,
ADD COLUMN has_broker BOOLEAN DEFAULT false,
ADD COLUMN broker_id UUID REFERENCES partners(id),
ADD COLUMN marketing_smartlink BOOLEAN DEFAULT false,
ADD COLUMN marketing_board BOOLEAN DEFAULT false,
ADD COLUMN marketing_banner BOOLEAN DEFAULT false,
ADD COLUMN marketing_banner_property BOOLEAN DEFAULT false,
ADD COLUMN marketing_paid_traffic BOOLEAN DEFAULT false,
ADD COLUMN marketing_facebook_group BOOLEAN DEFAULT false,
ADD COLUMN marketing_whatsapp_group BOOLEAN DEFAULT false,
ADD COLUMN marketing_flyer BOOLEAN DEFAULT false,
ADD COLUMN marketing_influencer BOOLEAN DEFAULT false,
ADD COLUMN cca_id UUID REFERENCES partners(id),
ADD COLUMN marketing_ad_copy TEXT,
ADD COLUMN appraisal_status TEXT,
ADD COLUMN appraisal_notes TEXT,
ADD COLUMN appraisal_date DATE,
ADD COLUMN sale_price NUMERIC,
ADD COLUMN cash_sale_discount NUMERIC;
